### ISSUE TITLE
pnpm create umi --template electron 创建项目失败

### ISSUE THREAD

**Issue by yangliuyu** [xiefengnian/umijs-electron-plugin#11]
按照文档 https://umijs.org/docs/guides/getting-started#%E4%BB%8E%E6%A8%A1%E6%9D%BF%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE
`pnpm create umi --template electron`
创建electron项目失败

https://github.com/umijs/umi/issues/11548#event-10156430944

![image](https://github.com/xiefengnian/umijs-electron-plugin/assets/1361821/7ca0f830-a5e3-4662-ba77-518facf372b8)

跟umijs-electron-plugin有关吗？如果是网络问题，换了taobao的镜像也是报错。
![image](https://github.com/xiefengnian/umijs-electron-plugin/assets/1361821/86896a5e-ce1c-4010-aa40-34c9b10a28d8)

**Comment by xiefengnian** [comment]
看起来是您没有把 @umiijs/electron-plugin 这个包下下来呀。https://registry.npmjs.com/@umijs/electron-template 是存在的，检查一下网络问题

**Comment by yangliuyu** [comment]
我打开了http的代理，关闭代理后，使用taobao镜像成功了

**Comment by xiefengnian** [comment]
> 

我发现了一些问题，确实使用 npm 源是找不到 @umijs/electron-template 这个包的，我尝试修复一下
