### ISSUE TITLE
index.html will not be packed into dist when build electron pack

### ISSUE THREAD

**Issue by TianQingshuai** [xiefengnian/umijs-electron-plugin#7]
.electron-production/render/index.html was generated after electron-builder task.
![image](https://user-images.githubusercontent.com/17986611/231756571-b49ded37-0a23-4492-b2da-87f571bbe150.png)

![image](https://user-images.githubusercontent.com/17986611/231756602-f7b74066-78ce-49a2-93a5-8f7647f4da69.png)

#https://github.com/xiefengnian/umijs-electron-template/issues/1

**Comment by iweb-wiki** [comment]
这个问题准备什么时候修复😅

**Comment by xiefengnian** [comment]
0.2.3 published
